build:
  id: 101
  version: 1.2.3
  name: "GIT DEV"
  type: "AQAmq5C6rNL65hCixN3tnBI2sR84Hd6YvG4Qbl6cz3UsGtj8ITRhuGrxi14djZnmT31HTmfUkTXfIa8iwArABvjvjpizy1/IWWY8M5uIEAg/jba1xadqpr19KDnRSZk8WiwlFJFKlfLQlRE/3DjpbrbIJojyPPqPGoLSvUdApdXB/nFyDYA0mIynQjUuRZl0ogx4zTaeTc3nkexK5mzbYb8UmqK4JEg+rtDd/D9+enfx+NxWMqR17LVSPe1hUuz+4jH+vH46V0IvM7TNG95sXhGrXhlcmA90BRGqyQm90ooH7jkPIx/j2q2Tfmop1PZfScx5zesWvfcHo4SxRLNFLkJxb9yWsG8O8O09s3UgVH+xLs24TIVR4Bu9aZxR/fhDCDIHzgR1w/9Zi2HiEjbqBI53"
